# Generated by Django 4.0.4 on 2022-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Vending Machine',
            },
        ),
    ]
