# Generated by Django 4.0.4 on 2022-05-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_vendingmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('refunded_amount', models.IntegerField()),
                ('currency', models.ManyToManyField(to='machine.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machine.product')),
            ],
            options={
                'verbose_name_plural': 'Transaction History',
            },
        ),
        migrations.DeleteModel(
            name='VendingMachine',
        ),
    ]
