# Generated by Django 4.0.4 on 2022-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_transactionhistory_delete_vendingmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='refunded_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
